#!/usr/bin/env fish
#
# Scripting tools for the fish shell
#
# Copyright © 2015 Simen Strange Øya
# Distributed under the Modified BSD license


function length 
	echo $argv[1] | wc -m | xargs printf "%u"
end

function flatten
	set list $argv[1..(count $argv)]
	#set out ""
	
	for el in $list
		set out $out $el " "
	end
	
	echo -ns $out
end

function status-out -d 'print $status to stdout'
	set cmd (flatten $argv[1..(count $argv)])
	eval $cmd
	echo $status
end

alias @1 status-out # @ is used a sign for status, and 1 is the FD for stdout